In [1]:
import numpy as np

In [2]:
def reverse(seq,i,j):
    seq[i:j] = seq[i:j][::-1]
    return seq

# 1. Greedy Algorithm 




* Simple Reversal Sort algorithm is not optimal 
    * For example we were able to solve [6 1 2 3 4 5] in two steps 
        *  invertthe fist element with the reset of the sequence  [5 4 3 2 1 | 6]
        *  invert the fist part [1 2 3 4 5 6]
* Note that optimal algorithms are unknown. Therefore approximation algorithms are used. 

In [3]:
# function :  simple_reverse_sort
# input    :  sequence
# output   :  sequence
def simple_reverse_sort(seq):
    n = len(seq)
    for i in range(n):
       j = np.where(seq == i+1)[0][0]
       if j != i: 
           j = j + 1
           seq[i:j] = seq[i:j][::-1]
           print(seq)
           simple_reverse_sort(seq)
       if np.array_equal(seq, np.arange(1,n+1)):   #Let suppose that seq start from 1 
           return seq        

In [7]:
# Example 1 
print(" Example 1")
seq_1 = np.array([1,2,3,4,5,6])
print("Sequence before", seq_1)
seq_2 = simple_reverse_sort(seq_1)
print("Sequence after",seq_2)

# Example 2
print("\n Example 2")
seq_1 = np.array([6,1,2,3,4,5])
print("Sequence before", seq_1)
print("Using Greedy Algo")
seq_2 = simple_reverse_sort(seq_1)
print("Sequence after",seq_2)


 Example 1
Sequence before [1 2 3 4 5 6]
Sequence after [1 2 3 4 5 6]

 Example 2
Sequence before [6 1 2 3 4 5]
Using Greedy Algo
[1 6 2 3 4 5]
[1 2 6 3 4 5]
[1 2 3 6 4 5]
[1 2 3 4 6 5]
[1 2 3 4 5 6]
Sequence after [1 2 3 4 5 6]


---

## Adjacencies and Breakpoints
* An adjacency : a pair of adjacent elements that are consecutive
* A breakpoint : a pair of adjacent elements that are not consecutive

Extending Permutations:
Is the process of adding 0 at the begining of a sequence and n+1 at the end, where n is the length of the sequence.

For example: Seq = [1 2 3 4 5 6]   become [ 0 1 2 3 4 5 6 7]  

In [8]:
# b : function 
# input : sequence 
# output: the number of break point of a given sequence seq
def b(seq): 
    total_break_points = 0
    for i in range(len(seq)-1):
        if np.abs(seq[i]-seq[i+1]) != 1:
            total_break_points += 1
    return total_break_points

In [10]:
# break sequence function
# input : sequence
# output : total_break_points: total number of break points
#          broke_seq: list of sub sequence 
#          break_point_indice : break point index in the sequence


def break_seq(seq):
    total_break_points = 0
    j = 0
    broke_seq = []
    break_point_indice = []
    for i in range(len(seq)-1):
        if np.abs(seq[i]-seq[i+1]) != 1:
            total_break_points += 1
            broke_seq.append(seq[j:i+1])
            break_point_indice.append(i+1)
            #print(seq[j:i+1])
            j = i+1
        
    return total_break_points, broke_seq, break_point_indice

In [27]:
def print_break_seq(seq,break_point_indice):
    result = ' '.join(f"| {num}" if i in break_point_indice else str(num) for i, num in enumerate(seq))
    return result.strip()

In [29]:
# Example 
seq = [6,5,3,1,2,4]

# Extending Permutations
seq = np.insert(seq,0,0)
seq = np.insert(seq,len(seq),len(seq))
# break sequence
total_break_points, broke_seq, break_point_indice = break_seq(seq)

print("Break sequence",print_break_seq(seq,break_point_indice))

print("Number of break points is ", total_break_points)
print("List of sub list",broke_seq)
print("list of indces", break_point_indice)


Break sequence 0 | 6 5 | 3 | 1 2 | 4 | 7
Number of break points is  5
List of sub list [array([0]), array([6, 5]), array([3]), array([1, 2]), array([4])]
list of indces [1, 3, 4, 6, 7]


## Reversal Distance and Breakpoints 

Each reversal eliminates at most 2 breakpoints. This implies: reversal distance ≥ number of breakpoints / 2

For example:
* Seq = [2 3 1 4 6 5]
* 1. Extend the permuation : 
    * Add 0 in the begining and n+1 in the end (n+1 = len(seq)+1 = 6+1 = 7). Seq = [0 2 3 1 4 6 5 7]
    * Calculate b(seq): number of break point in each step 
        *   [0 | 2 3 | 1 | 4 | 6 5 | 7] $\rightarrow$ b(seq) = 5
        *  the last element befor the break point is k = 0 with position i = 0, We inverse sequence from i+1 to j + 1, where j = 3 is the position of k+1 = 1. inverte(seq,i,j) function is used in this step  and we get [0 1 | 3 2 | 4 | 6 5 | 7] $\rightarrow$ b(seq) = 4
        * [0 1 2 3  4 | 6 5 | 7] $\rightarrow$ b(seq) = 2
        * [0 1 2 3  4 5 6  7] $\rightarrow$ b(seq) = 0

In [9]:
# To check this code
def break_point_reversal_sort(seq):
    while b(seq) > 0:
        # Among all possible reversals, choose reversal minimizing b(seq•reverse)
         break_point_reversal_sort(seq)

Problem:  There is a possibility that this algorithm will continue to function indefinitely.

## 3. Improved Breakpoint Reversal Sort

In [30]:
def strip(broke_seq):
    decreasing_list = []
    increasing_list = []
    for i in range (len(broke_seq)):
        sub_list = broke_seq[i]
        # if we have one element it is a incrasing strip
        if(len(sub_list) == 1): 
            increasing_list.append(sub_list)  
        elif (sub_list[0]-sub_list[1] == -1):
            increasing_list.append(sub_list)
        else:
            decreasing_list.append(sub_list)

    return increasing_list, decreasing_list

### code part 1

In [31]:
# This function return the indices of the sequence to invert, given decreasing_list
def get_ij_decreasing(seq, decreasing_list):
    a_min= 0
    k =  decreasing_list[0][0]
    
    for a in range(len(decreasing_list)):
        for b in range(len(decreasing_list[a])):
            if k > decreasing_list[a][b]:
                k = decreasing_list[a][b]
                a_min = a
    
    print("k =",k,"k-1 =",k-1)
    
    i = np.where(seq == k)[0][0] 
    j = np.where(seq == k-1)[0][0] 
    print("First ",i,j)
    if i < j:
        # min_sprit_first_value is the fist element of sublist that contain the min
        min_sprit_first_value = decreasing_list[a_min][0]
        i = np.where(seq == min_sprit_first_value)[0][0]
    else:
        # add code for j it should be the last element decreasing_list[a_min][-1]
        i,j = j+1, i+1
           
    print("Second ",i,j)
    return i,j

In [32]:
def get_ij_increasing(seq, increasing_list):
    last_list = None
    print(increasing_list)
    for sublist in reversed(increasing_list): 
        print(sublist)
        if len(sublist) > 1: 
            last_list = sublist 
            break

    a = last_list[0]
    b = last_list[-1]
    
    seq = np.array(seq)
    i = np.where(seq == a)[0][0] 
    j = np.where(seq == b)[0][0] + 1
    return i,j

In [33]:
seq = [6,5,3,1,2,4]
# 1. Add 0 and n 
seq = np.insert(seq,0,0)
seq = np.insert(seq,len(seq),len(seq))
print("Sequence ", seq)

total_break_points, broke_seq, break_point_indice = break_seq(seq)

# 2. if total_break_points != 0
while total_break_points != 0 : 
    increasing_list, decreasing_list = [], []
    # 2.1 get  increasing strip list and decreasing strip list from the broke list 
    increasing_list,decreasing_list = strip(broke_seq)
    print(increasing_list)
    print(decreasing_list)
    # 2.2 If decreasing_list.shape[0] != 0  reverse sequnce
    
    if len(decreasing_list)!= 0:
        i,j = get_ij_decreasing(seq, decreasing_list) #print(i,j)
        print(i,j)
    else:
        i,j = get_ij_increasing(seq, increasing_list) #

    print("i,j",i,j-1)
    seq = reverse(seq,i,j) 
    total_break_points, broke_seq, break_point_indice = break_seq(seq)
    print("Sequence with reverse",i,j-1,seq)  
    print("total breakpoints",total_break_points)  # There is an error here, total break point is always 6

Sequence  [0 6 5 3 1 2 4 7]
[array([0]), array([3]), array([1, 2]), array([4])]
[array([6, 5])]
k = 5 k-1 = 4
First  2 6
Second  1 6
1 6
i,j 1 5
Sequence with reverse 1 5 [0 2 1 3 5 6 4 7]
total breakpoints 5
[array([0]), array([3]), array([5, 6]), array([4])]
[array([2, 1])]
k = 1 k-1 = 0
First  2 0
Second  1 3
1 3
i,j 1 2
Sequence with reverse 1 2 [0 1 2 3 5 6 4 7]
total breakpoints 3
[array([0, 1, 2, 3]), array([5, 6]), array([4])]
[]
[array([0, 1, 2, 3]), array([5, 6]), array([4])]
[4]
[5 6]
i,j 4 5
Sequence with reverse 4 5 [0 1 2 3 6 5 4 7]
total breakpoints 2
[array([0, 1, 2, 3])]
[array([6, 5, 4])]
k = 4 k-1 = 3
First  6 3
Second  4 7
4 7
i,j 4 6
Sequence with reverse 4 6 [0 1 2 3 4 5 6 7]
total breakpoints 0


### Breakpoint Reversal Sort


In [42]:
index = [index for index, sublist in enumerate(broke_seq) if len(sublist) > 1]

seq_opt = seq.copy()
min_b = b(seq)
inverse_ij = []

while min_b != 0:
    #print(min_b)
    total_break_points, broke_seq, break_point_indice = break_seq(seq_opt)
    for k in range(len(break_point_indice)):
        sub_list = broke_seq[k]
        sub_list_length = len(sub_list)
        if sub_list_length > 1:
            j = break_point_indice[k]
            i = j - sub_list_length
            seq_1 = seq_opt.copy()
            seq_2 = reverse(seq_1,i,j)
            if b(seq_2) < min_b:
                seq_opt = seq_2.copy()
                min_b = b(seq_opt)
                #print(seq_opt) 
                inverse_ij.append([i,j-1]) 
        print(seq_opt)

print("in order to obtain the optimal sequcence is ", seq_opt, "\nwe invert element of postion:")
for ij in inverse_ij:
    print(ij[0],"",ij[1])


[0 6 5 3 1 2 4 7 8]
[0 6 5 3 1 2 4 7 8]
[0 6 5 3 1 2 4 7 8]
[0 6 5 3 2 1 4 7 8]
[0 6 5 3 2 1 4 7 8]
[0 6 5 3 2 1 4 7 8]
[0 6 5 3 2 1 4 7 8]
[0 6 5 1 2 3 4 7 8]
[0 6 5 1 2 3 4 7 8]
[0 6 5 1 2 3 4 7 8]
[0 6 5 1 2 3 4 7 8]
[0 6 5 4 3 2 1 7 8]
[0 6 5 4 3 2 1 7 8]
[0 1 2 3 4 5 6 7 8]
in order to obtain the optimal sequcence is  [0 1 2 3 4 5 6 7 8] 
we invert element of postion:
4  5
3  5
3  6
1  6
